application:
    message: hello world 1
spring:
  freemarker:
    template-loader-path: /freemarker/
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      time_format:  HH:mm:ss
      date_format: yyyy/MM/dd
    request-context-attribute: rc

logging:
  config: classpath:logback.xml
mysql:
  driverName: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  userName: root
  password: cuber
  minIdle: 2
  maxSize: 20